### ISSUE TITLE
Not an Issue, more a feature request

### ISSUE THREAD

**Issue by new-gen23** [123electric/smartbms-thingspeak#1]
Hi, 
I finally managed to get the 123smartbms installed and also bought the adapter. However, documentation how to connect the adapter via USB is very sparse (still no clue, how to connect the two cables to the out-board).

I wanted to just read the data from the smartbms to my Linux ELK stack. However, this project here pushed my private data directly to some third party@dunnowhere. So I have started to modify the code. Would would you be interested to publish a version that writes the BMS data to a local ELK stack (for privacy reasons) ?

**Comment by AlbertronicDev** [comment]
Hi,

I did not see your comment earlier, sorry for that.
You can create a branch and publish it with your own version if you want.

Installation instructions of the USB cable is [on the website](https://123electric.eu/products/123smartbms-to-usb/) (also nice-to-know for other users).
